name: Nebula
description: Demonstrates how to use the flutter_blue_plus plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.17.3
  flutter_launcher_icons: ^0.13.1
  flutter_foreground_task:
    git:
      url: https://github.com/Dev-hwang/flutter_foreground_task.git
      ref: a7e243ee56f251bc7f4d159ea8acaaee75fb22d3
  get: ^4.6.6
  shared_preferences: ^2.2.2
  notification_listener_service: ^0.3.3
  installed_apps: ^1.5.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: 'assets/images/icon.png'
  android: true
